### ISSUE TITLE
gitlab.com

### ISSUE THREAD

**Issue by ninuxio** [SnoringFrog/GitlabIntegrate#6]
- is GitlabIntegrate is compatible with gitlab.com?
- i can't find the get projects id command?

**Comment by SnoringFrog** [comment]
`get project id` changed to `select project id` back around version 1.2, but I apparently forgot reflect that change in some of the docs. I'll get right on that. 

As for gitlab.com, it should be compatible with it. Were you having any issues with it aside from not being able to find that command?

**Comment by dominiquedutra** [comment]
Hi there,
I am having trouble with gitlab.com as well.

All the options on the Tools > GitlabIntegrate are greyed out. My settings are as this:

```
 {
    //The project host
    "project_host":"http://gitlab.com",
  
    //Your user token for GitLab, found in [host]/profile/account 
    "user_token":"TOKEN",  
  
    //Displays the new installation window
    "display_intro":false,
    
    //The name of the tab when using Edit Issue In Tab (note: if you open another tab with this name, weird things might happen)
    "edit_issue_in_tab_name": "[GLI]: Editing Issue",
  
    //Suppresses output of closed issues for the Select Issue command
    "hide_closed_issues":false,
  
    //Appears before all GitlabIntegrate outputs in the console and status bar
    "output_prefix":"[GLI]:",
  
    /*
    The default project ID.
    This can be found by running GitlabIntegrate's "Get Project IDs" command after configuring 
    your host and user_token. All the projects you have access to should be listed with their IDs.
    */
    "project_id": 0 
  }
```

**Comment by ninuxio** [comment]
same here

**Comment by nickw444** [comment]
+1

**Comment by SnoringFrog** [comment]
Trying to figure this out myself, but GLI (which I haven't used or looked at in months) no longer seems to work for me on the projects I used to use it on, so I'm having difficulty figuring any of it out. May not be just a gitlab.com issue.

**Comment by SnoringFrog** [comment]
Worked on this all day today and can't seem to figure out why this happens. My test project works fine if I access the gitlab API directly, but not via the package. I suspect there is something in pyapi-gitlab that I'm overlooking that's causing the issue.

**Comment by nickw444** [comment]
I recall fixing this at one stage, it was an SSL thing i'm pretty sure. 

Wait turns out I did:
https://github.com/SnoringFrog/GitlabIntegrate/pull/7#event-336835379

**Comment by damko** [comment]
Same here

**Comment by zekeApps** [comment]
Same here... probably this is not yet maintained

**Comment by SnoringFrog** [comment]
I never did find a better fix for it. As far as I can tell, it's a pyapi issue that causes this. Haven't had much time (or, honestly, drive, since I don't use Gitlab or Sublime anymore) to convert all the pyapi calls to raw API calls, which _might_ remedy this.

**Comment by fbehrens** [comment]
It is working for me on GitLab Enterprise Edition 8.11.0-rc3-ee f21518a
